[workspace]
members = ["src-utility", "src-tauri", "crates/universal-function-macro"]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = "2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
